language: perl

# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
os: linux
dist: trusty

env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - EXTENDED_TESTING=1
    - RELEASE_TESTING=0
    - CFLAGS="-g -O2 -fstack-protector -Wformat -Werror=format-security"
    - CPPFLAGS="-D_FORTIFY_SOURCE=2"
    - CXXFLAGS="-g -O2 -fstack-protector -Wformat -Werror=format-security"
    - LDFLAGS="-Wl,-z,relro"

addons:
  apt:
    packages:
      - unzip
      - libaio1

jobs:
  fast_finish: true

  allow_failures:
    - perl: 'blead'
    - perl: '5.8'

# FYI Oracle XE only comes in utf8, so we can't run USASCII version of tests

  include:
# Perl 5.32 variations
## At 2020-09-03 Travis's 5.32 is broken
##    - perl: '5.32'
##      env:
##        - ORACLEV=11.2
##        - ORACLEDBV=11.2
##        - ORACLE_USERID=kermit/foobar
##        - ORACLE_USERID_2=mspiggy/barfoo
##        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'
##
##    - perl: '5.32'
##      env:
##        - ORACLEV=12.2
##        - ORACLEDBV=11.2
##        - ORACLE_USERID=kermit/foobar
##        - ORACLE_USERID_2=mspiggy/barfoo
##        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'
    - perl: '5.32-shrplib'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.32-shrplib'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

# Perl 5.28 variations
    - perl: '5.28'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.28'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'
    - perl: '5.28-shrplib'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.28-shrplib'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

# Perl 5.26 variations
    - perl: '5.26'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.26'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'
    - perl: '5.26-shrplib'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.26-shrplib'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

# Perl 5.24 variations
    - perl: '5.24'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.24'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.24-shrplib'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.24-shrplib'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.24-extras'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.24-extras'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

# Perl 5.22 variations
    - perl: '5.22'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.22'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.22-shrplib'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.22-shrplib'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.22-extras'
      env:
        - ORACLEV=11.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

    - perl: '5.22-extras'
      env:
        - ORACLEV=12.2
        - ORACLEDBV=11.2
        - ORACLE_USERID=kermit/foobar
        - ORACLE_USERID_2=mspiggy/barfoo
        - ORACLE_DSN='dbi:Oracle://localhost:1521/XE'

# Test without database, all tests should skip
    - perl: '5.26'
      env:
        - ORACLEV=11.2
        - COVERAGE=1
    - perl: '5.26'
      env:
        - ORACLEV=12.2
        - COVERAGE=1

before_install:
  - sudo maint/travis-ci_scripts/01_install_oracle_xe.bash
  - sudo maint/travis-ci_scripts/02_install_oracle_instantclient.bash
  - . /etc/profile
  - git config --global user.name "TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - perl -M5.014 -e1 2>/dev/null || cpan-install Dist::Zilla@5.047
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - pwd
  - coverage-setup

script:
  - perl Makefile.PL
  - make
#  - make test
  - prove -bv -r -s -j1 $(test-files)
  - ORACLE_USERID_2="" prove -bv t/60reauth.t
#  - dzil smoke --release --author

after_success:
  - coverage-report
